db:
  image: postgres:9.6-alpine
  container_name: web_db
  volumes:
   - /var/lib/postgresql/data
  ports:
   - "5432:5432"
  environment:
   - POSTGRES_DB=database
   - POSTGRES_USER=user
   - POSTGRES_PASSWORD=password

phpfpm:
  build: ./docker/php
  container_name: web_fpm
  links:
    - db:db
  ports:
   - "9000:9000"
  volumes:
   - .:/srv/http

nginx:
  image: nginx:1.15-alpine
  container_name: web_nginx
  links:
    - phpfpm:phpfpm
  ports:
   - "81:80"
   - "4433:443"
  volumes:
   - .:/usr/share/nginx/html
   - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf